import { Photo } from '../core/models/Photo';

export const PhotosStub: Photo[] = [
    {
        id: 1,
        title: 'pWkk7iiCoDM',
        url: 'https://source.unsplash.com/pWkk7iiCoDM/400x300',
        thumbnailUrl: 'https://source.unsplash.com/pWkk7iiCoDM/400x300',
    },
    {
        id: 2,
        title: 'aob0ukAYfuI',
        url: 'https://source.unsplash.com/aob0ukAYfuI/400x300',
        thumbnailUrl: 'https://source.unsplash.com/aob0ukAYfuI/400x300',
    },
    {
        id: 3,
        title: 'EUfxH-pze7s',
        url: 'https://source.unsplash.com/EUfxH-pze7s/400x300',
        thumbnailUrl: 'https://source.unsplash.com/EUfxH-pze7s/400x300',
    },
    {
        id: 4,
        title: 'M185_qYH8vg',
        url: 'https://source.unsplash.com/M185_qYH8vg/400x300',
        thumbnailUrl: 'https://source.unsplash.com/M185_qYH8vg/400x300',
    },
    {
        id: 5,
        title: 'sesveuG_rNo',
        url: 'https://source.unsplash.com/sesveuG_rNo/400x300',
        thumbnailUrl: 'https://source.unsplash.com/sesveuG_rNo/400x300',
    },
    {
        id: 6,
        title: 'AvhMzHwiE_0',
        url: 'https://source.unsplash.com/AvhMzHwiE_0/400x300',
        thumbnailUrl: 'https://source.unsplash.com/AvhMzHwiE_0/400x300',
    },
    {
        id: 7,
        title: '2gYsZUmockw',
        url: 'https://source.unsplash.com/2gYsZUmockw/400x300',
        thumbnailUrl: 'https://source.unsplash.com/2gYsZUmockw/400x300',
    },
    {
        id: 8,
        title: 'EMSDtjVHdQ8',
        url: 'https://source.unsplash.com/EMSDtjVHdQ8/400x300',
        thumbnailUrl: 'https://source.unsplash.com/EMSDtjVHdQ8/400x300',
    },
    {
        id: 9,
        title: '8mUEy0ABdNE',
        url: 'https://source.unsplash.com/8mUEy0ABdNE/400x300',
        thumbnailUrl: 'https://source.unsplash.com/8mUEy0ABdNE/400x300',
    },
    {
        id: 10,
        title: 'G9Rfc1qccH4',
        url: 'https://source.unsplash.com/G9Rfc1qccH4/400x300',
        thumbnailUrl: 'https://source.unsplash.com/G9Rfc1qccH4/400x300',
    },
    {
        id: 11,
        title: 'aJeH0KcFkuc',
        url: 'https://source.unsplash.com/aJeH0KcFkuc/400x300',
        thumbnailUrl: 'https://source.unsplash.com/aJeH0KcFkuc/400x300',
    },
    {
        id: 12,
        title: 'p2TQ-3Bh3Oo',
        url: 'https://source.unsplash.com/p2TQ-3Bh3Oo/400x300',
        thumbnailUrl: 'https://source.unsplash.com/p2TQ-3Bh3Oo/400x300',
    },
    {
        id: 13,
        title: 'pWkk7iiCoDM',
        url: 'https://source.unsplash.com/pWkk7iiCoDM/400x300',
        thumbnailUrl: 'https://source.unsplash.com/pWkk7iiCoDM/400x300',
    },
    {
        id: 14,
        title: 'aob0ukAYfuI',
        url: 'https://source.unsplash.com/aob0ukAYfuI/400x300',
        thumbnailUrl: 'https://source.unsplash.com/aob0ukAYfuI/400x300',
    },
    {
        id: 15,
        title: 'EUfxH-pze7s',
        url: 'https://source.unsplash.com/EUfxH-pze7s/400x300',
        thumbnailUrl: 'https://source.unsplash.com/EUfxH-pze7s/400x300',
    },
    {
        id: 16,
        title: 'M185_qYH8vg',
        url: 'https://source.unsplash.com/M185_qYH8vg/400x300',
        thumbnailUrl: 'https://source.unsplash.com/M185_qYH8vg/400x300',
    },
    {
        id: 17,
        title: 'sesveuG_rNo',
        url: 'https://source.unsplash.com/sesveuG_rNo/400x300',
        thumbnailUrl: 'https://source.unsplash.com/sesveuG_rNo/400x300',
    },
    {
        id: 18,
        title: 'AvhMzHwiE_0',
        url: 'https://source.unsplash.com/AvhMzHwiE_0/400x300',
        thumbnailUrl: 'https://source.unsplash.com/AvhMzHwiE_0/400x300',
    },
    {
        id: 19,
        title: '2gYsZUmockw',
        url: 'https://source.unsplash.com/2gYsZUmockw/400x300',
        thumbnailUrl: 'https://source.unsplash.com/2gYsZUmockw/400x300',
    },
    {
        id: 20,
        title: 'EMSDtjVHdQ8',
        url: 'https://source.unsplash.com/EMSDtjVHdQ8/400x300',
        thumbnailUrl: 'https://source.unsplash.com/EMSDtjVHdQ8/400x300',
    },
    {
        id: 21,
        title: '8mUEy0ABdNE',
        url: 'https://source.unsplash.com/8mUEy0ABdNE/400x300',
        thumbnailUrl: 'https://source.unsplash.com/8mUEy0ABdNE/400x300',
    },
    {
        id: 22,
        title: 'G9Rfc1qccH4',
        url: 'https://source.unsplash.com/G9Rfc1qccH4/400x300',
        thumbnailUrl: 'https://source.unsplash.com/G9Rfc1qccH4/400x300',
    },
    {
        id: 23,
        title: 'aJeH0KcFkuc',
        url: 'https://source.unsplash.com/aJeH0KcFkuc/400x300',
        thumbnailUrl: 'https://source.unsplash.com/aJeH0KcFkuc/400x300',
    },
    {
        id: 24,
        title: 'p2TQ-3Bh3Oo',
        url: 'https://source.unsplash.com/p2TQ-3Bh3Oo/400x300',
        thumbnailUrl: 'https://source.unsplash.com/p2TQ-3Bh3Oo/400x300',
    },
];
